name: build
on:
  pull_request:
    paths:
      - "code/**"

  push:
    paths:
      - "code/**"

jobs:
  test-matrix:
    strategy:
      matrix:
        arduino-platform: ["rp2040:rp2040"]
        include:
          - arduino-platform: "rp2040:rp2040"
            fqbn: "rp2040:rp2040:rpipico"

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Arduino CLI
        uses: arduino/setup-arduino-cli@v1

      - name: Install platform
        run: |
          arduino-cli core update-index --additional-urls https://github.com/earlephilhower/arduino-pico/releases/download/global/package_rp2040_index.json
          arduino-cli core install ${{ matrix.arduino-platform }}@2.6.5 --additional-urls https://github.com/earlephilhower/arduino-pico/releases/download/global/package_rp2040_index.json

      - name: Install libs
        run: |
          arduino-cli lib install "Adafruit Protomatter"
          arduino-cli lib install "ArduinoThread"

      - name: Compile Sketch
        run: arduino-cli compile -b ${{ matrix.fqbn }} --export-binaries code/display/display.ino

      - name: Upload binaries
        uses: actions/upload-artifact@v3
        with:
          name: boes-binaries
          path: code/display/build/
