name: Full KiCad documentation

on:
  workflow_dispatch:
    inputs:
      KiBot-Verbosity:
        description: "Log levels for KiBot"
        required: false
        default: "0"
        type: choice
        options:
          - "0"
          - "1"
          - "2"
          - "3"

jobs:
  # Uploads an artifact
  Main_PCB_full_docs:
    uses: AntarktisZ11/reusable-workflows/.github/workflows/kicad_test_all.yaml@main
    with:
      KiCadProjectName: boes
      KiCadProjectDir: pcb
      KiBot-Verbosity: ${{ inputs.KiBot-Verbosity || '0' }}

  # Uploads an artifact
  Sensor_PCB_full_docs:
    uses: AntarktisZ11/reusable-workflows/.github/workflows/kicad_test_all.yaml@main
    with:
      KiCadProjectName: boes_sensor
      KiCadProjectDir: pcb
      KiBot-Verbosity: ${{ inputs.KiBot-Verbosity || '0' }}
